version: '3.8'

services:
  rocket-league-coach:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    environment:
      - ENVIRONMENT=production
      - LOG_LEVEL=INFO
      - BALLCHASING_API_TOKEN=${BALLCHASING_API_TOKEN}
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - rl-coach-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  rl-coach-network:
    driver: bridge
